# Data bilan tanishuv

In [ ]:
#kutubxonalarni chaqirish(#install qiling !pip install pandas)
import pandas as pd

In [15]:
df=pd.read_csv('train.csv')

In [16]:
df.head()# Dastlabki 5 ta qatorni ko'rsatadi

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [11]:
df.head(50)

    Temperature   Humidity  Wind_Speed  Cloud_Cover     Pressure     Rain
0     23.720338  89.592641    7.335604    50.501694  1032.378759     rain
1     27.879734  46.489704    5.952484     4.990053   992.614190  no rain
2     25.069084  83.072843    1.371992    14.855784  1007.231620  no rain
3     23.622080  74.367758    7.050551    67.255282   982.632013     rain
4     20.591370  96.858822    4.643921    47.676444   980.825142  no rain
5     26.147353  48.217260   15.258547    59.766279  1049.738751  no rain
6     20.939680  40.799444    2.232566    45.827508  1014.173766  no rain
7     32.294325  51.848471    2.873621    92.551497  1006.041733  no rain
8     34.091569  48.057114    5.570206    82.524873   993.732047  no rain
9     19.586038  82.978293    5.760537    98.014450  1036.503457     rain
10    29.793126  81.317651   16.926099    93.923294  1029.402690  no rain
11    23.222373  76.877943   15.825673    72.869790   980.108934     rain
12    24.201114  45.146538   11.572713     5.253042  1033.985867  no rain
13    33.139916  90.326477    5.771774    99.910178   987.803792  no rain
14    11.775901  96.960009    6.377567    47.331870  1046.404288  no rain
15    12.178232  67.212407   11.844365     6.099704  1003.291526  no rain
16    10.505460  75.456091   14.797331    99.142331  1011.577194     rain
17    30.815496  65.048447    7.681961    57.037672   980.348663  no rain
18    29.453919  49.849040   10.191241    45.900402  1037.707488  no rain
19    31.750304  50.030332   17.760663     1.978943  1001.571778  no rain
20    34.465459  51.939437   12.995817    42.840117  1018.951281  no rain
21    29.978964  43.359500   10.711003    18.327075  1044.862056  no rain
22    21.536984  93.134654    1.424449    71.894899   990.935567     rain
23    29.513229  90.087869    3.520304     0.786690  1040.713073  no rain
24    12.956861  62.314755    4.019832    53.303568  1015.016725  no rain
25    25.998026  55.707599   12.462966     4.371622  1044.711932  no rain
26    13.583832  95.735485    2.162255    71.483000  1037.564854     rain
27    33.616723  45.566143    0.579897    95.301949  1011.008602  no rain
28    23.046208  68.747937    7.207011     4.332055   986.209824  no rain
29    20.366548  33.814871   14.377184    10.308416   982.113822  no rain
30    16.613890  43.384154   13.864987    51.559297  1041.196157  no rain
31    29.355842  72.281885   15.853407    98.246210  1013.199944  no rain
32    21.403758  76.352856   13.924965    41.145673  1026.458644  no rain
33    24.210849  70.669707   12.265712    61.557295  1041.715389     rain
34    10.469745  90.872099    9.723242    76.165333  1001.326129     rain
35    25.440887  99.538365    4.169966    92.792009  1042.703411  no rain
36    25.302393  83.470329   11.370961    17.701665   981.927271  no rain
37    25.423350  62.556425   12.732495    91.142602   999.594798  no rain
38    33.593702  88.375427    2.474867    62.642425  1036.823648  no rain
39    27.045507  38.427118   11.302947    80.560692  1039.725422  no rain
40    18.987698  77.828949    1.954974    29.555522  1046.138478  no rain
41    20.925799  66.283645   10.941536    50.010096  1001.210789  no rain
42    27.440780  42.464612    3.178378    20.895919  1034.616491  no rain
43    11.505637  98.105353    2.380271    85.460413  1048.959121     rain
44    26.669168  53.690619    2.262001    20.457909  1016.890421  no rain
45    26.765947  73.079638   18.220506    54.832678   997.681740  no rain
46    15.259564  91.501597   11.961746    41.791321   982.727362  no rain
47    13.223157  65.468219    5.003174     4.958951  1033.175714  no rain
48    17.885709  38.059650    1.428978    41.214765   989.719177  no rain
49    19.092769  87.311736   10.723628    78.439742  1007.085982     rain

In [14]:
df.tail()

      Temperature   Humidity  Wind_Speed  Cloud_Cover     Pressure     Rain
2495    21.791602  45.270902   11.807192    55.044682  1017.686181  no rain
2496    27.558479  46.481744   10.884915    39.715133  1008.590961  no rain
2497    28.108274  43.817178    2.897128    75.842952   999.119187  no rain
2498    14.789275  57.908105    2.374717     2.378743  1046.501875  no rain
2499    26.554356  97.101517   18.563084    81.357508  1001.729176  no rain

In [17]:
df.head()

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S