# Data bilan tanishuv

In [2]:
#kutubxonalarni chaqirish(#install qiling !pip install pandas)
import pandas as pd

In [24]:
df=pd.read_csv('train.csv')

In [6]:
df.head(892)# Dastlabki 5 ta qatorni ko'rsatadi

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [11]:
df.head(50)

    Temperature   Humidity  Wind_Speed  Cloud_Cover     Pressure     Rain
0     23.720338  89.592641    7.335604    50.501694  1032.378759     rain
1     27.879734  46.489704    5.952484     4.990053   992.614190  no rain
2     25.069084  83.072843    1.371992    14.855784  1007.231620  no rain
3     23.622080  74.367758    7.050551    67.255282   982.632013     rain
4     20.591370  96.858822    4.643921    47.676444   980.825142  no rain
5     26.147353  48.217260   15.258547    59.766279  1049.738751  no rain
6     20.939680  40.799444    2.232566    45.827508  1014.173766  no rain
7     32.294325  51.848471    2.873621    92.551497  1006.041733  no rain
8     34.091569  48.057114    5.570206    82.524873   993.732047  no rain
9     19.586038  82.978293    5.760537    98.014450  1036.503457     rain
10    29.793126  81.317651   16.926099    93.923294  1029.402690  no rain
11    23.222373  76.877943   15.825673    72.869790   980.108934     rain
12    24.201114  45.146538   11.572713     5.253042  1033.985867  no rain
13    33.139916  90.326477    5.771774    99.910178   987.803792  no rain
14    11.775901  96.960009    6.377567    47.331870  1046.404288  no rain
15    12.178232  67.212407   11.844365     6.099704  1003.291526  no rain
16    10.505460  75.456091   14.797331    99.142331  1011.577194     rain
17    30.815496  65.048447    7.681961    57.037672   980.348663  no rain
18    29.453919  49.849040   10.191241    45.900402  1037.707488  no rain
19    31.750304  50.030332   17.760663     1.978943  1001.571778  no rain
20    34.465459  51.939437   12.995817    42.840117  1018.951281  no rain
21    29.978964  43.359500   10.711003    18.327075  1044.862056  no rain
22    21.536984  93.134654    1.424449    71.894899   990.935567     rain
23    29.513229  90.087869    3.520304     0.786690  1040.713073  no rain
24    12.956861  62.314755    4.019832    53.303568  1015.016725  no rain
25    25.998026  55.707599   12.462966     4.371622  1044.711932  no rain
26    13.583832  95.735485    2.162255    71.483000  1037.564854     rain
27    33.616723  45.566143    0.579897    95.301949  1011.008602  no rain
28    23.046208  68.747937    7.207011     4.332055   986.209824  no rain
29    20.366548  33.814871   14.377184    10.308416   982.113822  no rain
30    16.613890  43.384154   13.864987    51.559297  1041.196157  no rain
31    29.355842  72.281885   15.853407    98.246210  1013.199944  no rain
32    21.403758  76.352856   13.924965    41.145673  1026.458644  no rain
33    24.210849  70.669707   12.265712    61.557295  1041.715389     rain
34    10.469745  90.872099    9.723242    76.165333  1001.326129     rain
35    25.440887  99.538365    4.169966    92.792009  1042.703411  no rain
36    25.302393  83.470329   11.370961    17.701665   981.927271  no rain
37    25.423350  62.556425   12.732495    91.142602   999.594798  no rain
38    33.593702  88.375427    2.474867    62.642425  1036.823648  no rain
39    27.045507  38.427118   11.302947    80.560692  1039.725422  no rain
40    18.987698  77.828949    1.954974    29.555522  1046.138478  no rain
41    20.925799  66.283645   10.941536    50.010096  1001.210789  no rain
42    27.440780  42.464612    3.178378    20.895919  1034.616491  no rain
43    11.505637  98.105353    2.380271    85.460413  1048.959121     rain
44    26.669168  53.690619    2.262001    20.457909  1016.890421  no rain
45    26.765947  73.079638   18.220506    54.832678   997.681740  no rain
46    15.259564  91.501597   11.961746    41.791321   982.727362  no rain
47    13.223157  65.468219    5.003174     4.958951  1033.175714  no rain
48    17.885709  38.059650    1.428978    41.214765   989.719177  no rain
49    19.092769  87.311736   10.723628    78.439742  1007.085982     rain

In [7]:
df.tail()

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [9]:
df

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [10]:
# Datalar xaqida umumiy malumot olish
#1Qancha ustun borligi va qator
#2 Data preprocessing uchun kerakli bilimlarni olish
#3 Malumot turlarini ko'rish
#4 Memory usageni aniqlash

In [ ]:
df.info()# data haqida umumiy malutot beradi

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Gender       891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48841 entries, 0 to 48840
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   39             48841 non-null  int64
 1   State-gov      48841 non-null  object
 2   77516          48841 non-null  int64
 3   Bachelors      48841 non-null  object
 4   13             48841 non-null  int64
 5   Never-married  48841 non-null  object
 6   Adm-clerical   48841 non-null  object
 7   Not-in-family  48841 non-null  object
 8   White          48841 non-null  object
 9   Male           48841 non-null  object
 10  2174           48841 non-null  int64
 11  0              48841 non-null  int64
 12  40             48841 non-null  int64
 13  United-States  48841 non-null  object
 14  <=50K          48841 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.6+ MB

In [20]:
df.head()

,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K

In [17]:
df['Pclass']

0      3
1      1
2      3
3      1
4      3
      ..
886    2
887    1
888    3
889    1
890    3
Name: Pclass, Length: 891, dtype: int64

In [13]:
df['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [14]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Gender           0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [21]:
df.head()

,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K

In [ ]:
df.describe()   # Dataset xaqida statistic malumot olish

,39,77516,13,2174,0,40
count,48841.000000,4.884100e+04,48841.000000,48841.000000,48841.000000,48841.000000
mean,38.643578,1.896664e+05,10.078029,1079.045208,87.504105,40.422391
std,13.710650,1.056039e+05,2.570965,7452.093700,403.008483,12.391571
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.175550e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.781470e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.376460e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.490400e+06,16.000000,99999.000000,4356.000000,99.000000

In [23]:
df.head()

,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K

In [25]:
df.head()

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [26]:
df['Ticket'].value_counts()

Ticket
347082      7
CA. 2343    7
1601        7
3101295     6
CA 2144     6
           ..
9234        1
19988       1
2693        1
PC 17612    1
370376      1
Name: count, Length: 681, dtype: int64

In [27]:
df['Gender'].value_counts()

Gender
male      577
female    314
Name: count, dtype: int64

In [28]:
df['Ticket'].nunique()

681

In [29]:
df['Gender'].nunique()

2